import 'server-only';

import { listCategory, type Listing } from '@/lib/marketplace';
import { getProbeStore } from '@/lib/history/store';
import { buildTrackRecord, type TrackRecord } from '@/lib/history/record';
import { toSweepAttestation } from '@/lib/history/attest';
import { summariseProof } from '@/lib/proof/engine';
import { computeScore } from '@/lib/score/engine';
import { BSC_MAINNET } from '@/lib/scan/types';
import type { Brief, Match, Recommendation, Rejection } from './types';
import { MIN_PROBES, MIN_UPTIME } from './thresholds';


const HISTORY_DAYS = 30;

/**
 * Things this engine genuinely cannot assess, stated plainly.
 *
 * The registry publishes no capital limits, realised returns, or drawdown, so a
 * recommendation cannot weigh them. Listing them here keeps the UI honest
 * without weakening the parts that are real.
 */
function limitationsFor(brief: Brief): string[] {
  return [
    `Capital compatibility is not assessed. No agent in the registry publishes a minimum or maximum position size, so we cannot confirm any of these suit ${brief.capital.toLocaleString('en-US', { style: 'currency', currency: 'USD', maximumFractionDigits: 0 })} specifically.`,
    'Returns and drawdown are not assessed. No measurer attests to realised performance, so ranking is based on reliability and evidence rather than profit.',
    'Reliability measures whether an agent responds, not whether its decisions are good. A perfectly available agent can still trade badly.',
  ];
}

/** Fit is about this brief; the Pokter Score is about the agent. They differ. */
function assessFit(
  listing: Listing,
  record: TrackRecord,
  scoreOverall: number | null,
  brief: Brief,
): { fit: number; reasons: string[]; tradeoffs: string[] } {
  const reasons: string[] = [];
  const tradeoffs: string[] = [];

  const uptime =
    record.totalProbes === 0 ? null : record.totalAnswered / record.totalProbes;

  // Reliability against the user's stated tolerance.
  const required = MIN_UPTIME[brief.risk];
  let fit = 0;

  if (uptime !== null) {
    fit += Math.min(1, uptime / required) * 0.4;
    if (uptime >= required) {
      reasons.push(
        `Answered ${(uptime * 100).toFixed(1)}% of ${record.totalProbes} probes, clearing the ${(required * 100).toFixed(0)}% bar for ${brief.risk} risk tolerance.`,
      );
    }
  }

  // Evidence depth.
  if (listing.attestationCount > 0) {
    fit += 0.2;
    reasons.push(
      `Carries ${listing.attestationCount} independent on-chain attestation(s), not just self-description.`,
    );
  } else {
    tradeoffs.push(
      'No third-party measurer has attested to this agent; the only evidence is Pokter’s own probing.',
    );
  }

  // Observation length against the user's horizon. Watching an agent for two
  // days says little about how it behaves over ninety.
  const observed = record.observedDays;
  const horizonCoverage = brief.horizon === 0 ? 0 : observed / brief.horizon;
  fit += Math.min(1, horizonCoverage) * 0.2;

  if (horizonCoverage < 0.25) {
    tradeoffs.push(
      `Observed for ${observed < 1 ? 'under a day' : `${Math.round(observed)} day(s)`}, well short of your ${brief.horizon}-day horizon.`,
    );
  }

  // Quality of the agent itself.
  if (scoreOverall !== null) {
    fit += (scoreOverall / 100) * 0.2;
  }

  if (record.longestOutage && record.longestOutage.probes > 2) {
    tradeoffs.push(
      `Had a sustained outage of ${record.longestOutage.probes} consecutive failed probes.`,
    );
  }

  const protocols = listing.agent.supported_protocols ?? [];
  if (protocols.length > 0) {
    reasons.push(`Publishes a reachable ${protocols.join(' / ')} endpoint.`);
  }

  return { fit: Math.min(1, fit), reasons, tradeoffs };
}

/**
 * §25 / §52. Produce a recommendation for a brief.
 *
 * Filtering is explicit and every rejection carries a reason the user can
 * check — the "why not?" answer is generated by the same pass that does the
 * filtering, so the explanation can never drift from the decision.
 */
export async function recommend(brief: Brief): Promise<Recommendation> {
  const store = getProbeStore();
  const since = new Date(Date.now() - HISTORY_DAYS * 86_400_000);

  const candidates = await listCategory(brief.objective, {
    chainId: BSC_MAINNET,
    limit: 12,
  });

  const rejected: Rejection[] = [];
  const matches: Match[] = [];

  for (const listing of candidates) {
    const record = buildTrackRecord(
      store.historyFor(listing.agent.chain_id, listing.agent.token_id, since),
    );

    const protocols = listing.agent.supported_protocols ?? [];
    if (protocols.length === 0) {
      rejected.push({
        listing,
        reason: 'Publishes no service endpoint, so it cannot be verified or hired.',
      });
      continue;
    }

    if (record.totalProbes === 0) {
      rejected.push({
        listing,
        reason:
          'Pokter has not measured this agent yet, so there is no track record to judge it on.',
      });
      continue;
    }

    const uptime = record.totalAnswered / record.totalProbes;

    if (uptime === 0) {
      rejected.push({
        listing,
        reason: `Answered none of ${record.totalProbes} probes — the endpoint is not responding.`,
      });
      continue;
    }

    if (uptime < MIN_UPTIME[brief.risk]) {
      rejected.push({
        listing,
        reason: `Answered ${(uptime * 100).toFixed(0)}% of probes, below the ${(MIN_UPTIME[brief.risk] * 100).toFixed(0)}% required for ${brief.risk} risk tolerance.`,
      });
      continue;
    }

    if (record.totalProbes < MIN_PROBES[brief.risk]) {
      rejected.push({
        listing,
        reason: `Only ${record.totalProbes} probe(s) recorded; ${MIN_PROBES[brief.risk]} are required before recommending at ${brief.risk} risk.`,
      });
      continue;
    }

    // Build the full score for survivors only — it is the expensive part.
    const sweep = toSweepAttestation(record, {
      agentId: listing.agent.id,
      chainId: listing.agent.chain_id,
    });
    const proof = summariseProof(sweep ? [sweep] : []);
    const score = computeScore({
      agent: listing.agent,
      category: brief.objective,
      proof,
      attestations: sweep ? [sweep] : [],
      record,
    });

    const { fit, reasons, tradeoffs } = assessFit(listing, record, score.overall, brief);
    matches.push({ listing, record, score, fit, reasons, tradeoffs });
  }

  matches.sort((a, b) => b.fit - a.fit);

  return {
    brief,
    recommended: matches[0] ?? null,
    alternatives: matches.slice(1, 4),
    rejected,
    considered: candidates.length,
    limitations: limitationsFor(brief),
  };
}
