const starterConfigSchema = {
  $schema: 'https://json-schema.org/draft/2020-12/schema',
  $id: 'https://pokter.xyz/schemas/starter-config-v1',
  title: 'Pokter agent starter configuration',
  description: 'Portable handoff generated by Pokter for an agent runtime. The runtime remains responsible for enforcing every selected behavior.',
  type: 'object',
  additionalProperties: false,
  required: ['schema', 'agent', 'category', 'protocol', 'behavior', 'note'],
  properties: {
    schema: { const: 'https://pokter.xyz/schemas/starter-config-v1' },
    agent: { type: 'string', minLength: 1, maxLength: 80 },
    category: { enum: ['rebalancing', 'grid-trading', 'yield', 'health-factor'] },
    protocol: { enum: ['a2a', 'mcp'] },
    behavior: {
      type: 'object',
      additionalProperties: false,
      required: ['target', 'policy', 'output'],
      properties: {
        target: { type: 'string', minLength: 1, maxLength: 120 },
        policy: { type: 'string', minLength: 1, maxLength: 120 },
        output: { type: 'string', minLength: 1, maxLength: 120 },
      },
    },
    note: { type: 'string', minLength: 1, maxLength: 300 },
  },
} as const;

export function GET() {
  return Response.json(starterConfigSchema, {
    headers: {
      'cache-control': 'public, max-age=3600, stale-while-revalidate=86400',
      'x-content-type-options': 'nosniff',
    },
  });
}
